package tests;

public class TestData {
    public static  String thousandOfWords = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod dolor sed tincidunt porta. Cras sed risus quis tellus consectetur interdum nec vitae ligula. Nulla pellentesque justo at imperdiet scelerisque. Phasellus mauris nunc, tempus id erat vitae, finibus semper tortor. Donec tortor dolor, tristique eu ipsum non, venenatis fringilla ante. Proin id ullamcorper eros. Praesent aliquet quam eget nisi tempus condimentum. Aenean mollis erat nulla, sit amet laoreet leo condimentum in. Nunc laoreet vestibulum pulvinar. Cras lobortis gravida posuere. Praesent pulvinar metus vitae ex pretium sollicitudin. Duis nec volutpat sem. Sed iaculis leo dui, eu egestas ex tristique at. In et magna a justo tempor ornare."+
            "Integer aliquam eu libero ut rutrum. Suspendisse ullamcorper vitae neque et lobortis. Maecenas in feugiat felis. Aliquam suscipit cursus quam vitae eleifend. Pellentesque consequat ultricies consequat. Aenean rutrum vel orci laoreet convallis. Proin vitae molestie dolor. Phasellus venenatis ante in ligula eleifend tincidunt. Aenean ultricies elit dolor, quis vehicula urna tempor et. In risus diam, venenatis mollis massa eu, vehicula auctor diam. Morbi accumsan est justo, a sodales nisi accumsan et. Aenean sed arcu mattis, dictum massa a, rhoncus dui. Fusce ac est in nisi ultrices tempor vestibulum at nibh. Ut mattis velit nec justo eleifend auctor. Nullam vel nulla turpis. Nulla sagittis finibus magna."+
            "Duis pretium at mi at suscipit. Sed commodo tempor augue, ut blandit leo egestas at. Praesent non vehicula urna. Pellentesque at pellentesque ex. Etiam dictum ornare eleifend. Maecenas tincidunt massa a neque pretium, eget dapibus nulla mattis. Proin urna nibh, tempus efficitur lectus eget, feugiat efficitur dolor. Nunc eu libero elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent mattis vehicula urna, sit amet porttitor quam lobortis non. Phasellus aliquet tristique efficitur. Ut vel ex purus. Donec pharetra in enim at scelerisque. Nam sed sem bibendum, euismod ipsum sed, rutrum orci. Morbi enim nulla, venenatis sit amet dolor vel, fringilla convallis est."+
            "Suspendisse porta mauris eu lectus varius, vel consequat massa fermentum. Integer tristique quis nunc a sagittis. Curabitur sed dapibus leo. Morbi venenatis nisl elit, in rutrum tortor faucibus et. In eu magna neque. Pellentesque aliquet ut lorem ac sodales. Fusce convallis dolor eleifend massa iaculis tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce ultricies vitae justo congue imperdiet. Donec id purus eleifend, tincidunt nulla eget, vulputate libero. Quisque at mattis erat. Phasellus malesuada gravida tincidunt. Aenean venenatis ac mauris ut auctor."+
            "Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras iaculis rutrum augue, ut porta lorem iaculis at. Duis sagittis ipsum ac odio iaculis, at eleifend libero egestas. Aliquam ut lectus nulla. Sed mollis quam urna, vel imperdiet ante elementum id. Morbi aliquam lacus eget turpis fringilla, nec interdum nisi efficitur. Nullam tempor pretium orci, a fermentum justo tempor blandit. Nullam in odio nec urna pellentesque auctor et at quam. Donec tincidunt metus tellus, in sagittis lacus vestibulum ut. Praesent commodo est eu lectus interdum mattis. Nam non leo eu nunc consequat semper vel in ligula."+
            "Aliquam ac enim eros. Proin diam ligula, vehicula quis ex placerat, sollicitudin tristique quam. Sed imperdiet ex ut ante accumsan, ut cursus leo faucibus. Morbi sed pretium nisi. Fusce non massa quis est pharetra sagittis vel nec erat. Donec scelerisque pulvinar libero, et laoreet justo dignissim ac. Suspendisse eget pharetra nibh. Donec a interdum ligula. Ut posuere in nulla nec facilisis. Duis metus elit, cursus ut sapien sit amet, dignissim elementum odio. Fusce ut viverra est, a aliquam lectus. Mauris risus orci, lobortis vel tincidunt eget, tristique ac sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce tempus dignissim placerat. Nunc iaculis ultrices ipsum sed fringilla."+
            "Phasellus aliquam turpis et ligula placerat imperdiet eu sit amet est. Curabitur venenatis, urna ut lobortis euismod, quam nisl faucibus justo, a luctus ipsum neque sed libero. Sed sagittis ligula risus, sit amet elementum arcu consectetur at. Maecenas dictum urna sed auctor gravida. Aliquam iaculis ante at maximus accumsan. Cras dui mauris, scelerisque vel dui id, ornare imperdiet tortor. Maecenas sit amet metus ut sem tristique venenatis ac eget lacus. Etiam vel mauris scelerisque, dignissim nisl a, sollicitudin justo. Donec risus ligula, finibus sed lectus vel, consectetur vulputate eros. Mauris sit amet porta ante, sed gravida urna. Proin dui orci, aliquam pellentesque consequat non, mattis id ipsum."+
            "Phasellus vitae consequat velit, volutpat fermentum orci. Morbi sed odio sed urna facilisis egestas sit amet eget urna. Donec diam diam, sodales in bibendum laoreet, placerat eget nibh. Aliquam ut cursus ligula, vel lobortis metus. Pellentesque ullamcorper, diam lobortis congue sodales, arcu sapien feugiat felis, ut dignissim ante orci nec elit. Suspendisse metus arcu, luctus ut condimentum sed, semper eget tellus. Maecenas at pulvinar libero. In mauris ligula, laoreet ut purus vel, suscipit facilisis felis. Phasellus vehicula sem luctus arcu consectetur congue. Nunc consectetur neque tincidunt luctus porttitor. Pellentesque aliquam tempor nibh. Ut non semper nibh."+
            "Aliquam venenatis tincidunt tellus, tristique consectetur nulla ullamcorper nec. Nunc nec mauris sem. Sed lacinia turpis eu libero hendrerit aliquam. Aenean id venenatis libero. Donec sit amet mi in massa lacinia facilisis at quis nisi. Etiam purus erat, venenatis in velit ut, blandit suscipit elit. Praesent aliquet interdum molestie. Nunc augue nibh, ornare non gravida at, interdum vel dolor. Cras molestie accumsan ultrices. Suspendisse eget turpis quis magna venenatis elementum. Phasellus vehicula, risus luctus tristique vulputate, massa velit sagittis mi, et bibendum est massa vel massa. Donec felis massa, rhoncus sed fringilla vel, finibus ac urna. Phasellus nec ultrices lacus, non varius nibh. In sagittis risus et risus blandit, nec facilisis sem feugiat. Vestibulum lorem lorem, suscipit id elit sed, ultricies facilisis erat."+
            "Mauris eu auctor quam, sit amet tempus justo. Nam fermentum odio eget sem posuere semper. Integer scelerisque felis tempus tellus sollicitudin, vitae consectetur turpis scelerisque. Praesent nec porttitor orci, sed rhoncus mauris. Fusce consequat quis metus eget ultricies. Nunc interdum blandit condimentum. Nulla suscipit iaculis accumsan. Vivamus tristique tempor consectetur. Curabitur pretium ligula ante, et faucibus diam consectetur sit amet. Etiam. ";

    public static String  elevenMessages = "\n" +
            "\n" +
            "Proin iaculis auctor ante, non elementum est aliquet ac. Sed at nisl sed lacus tempor vestibulum.\n" +
            "\n" +
            "Sed nec ipsum pharetra, pharetra neque ut, egestas ante. \n" +
            "\n" +
            "Morbi vitae volutpat massa. Sed ultrices a elit ut tempus.uisque ut diam diam. \n" +
            "\n" +
            "Vestibulum a diam vitae augue sollicitudin elementum.\n" +
            "\n" +
            "Maecenas id sapien tincidunt, mollis odio in, convallis orci. \n" +
            "\n" +
            "Fusce quis velit aliquet, ultricies nulla ac, ullamcorper risus. \n" +
            "\n" +
            "Aenean pellentesque consectetur massa. Integer mattis viverra aliquam.\n" +
            "\n" +
            "Phasellus semper vitae velit ut tincidunt. \n" +
            "\n" +
            "Maecenas tempus nisl a neque condimentum, sed lobortis erat tempus.\n" +
            "\n" +
            "Praesent tristique elementum velit sit amet sollicitudin.\n" +
            "\n" +
            "Donec arcu mi, pulvinar eu dolor sit amet, pretium maximus turpis.";

}
